# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import event_attendees.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeedetails',
            name='attendee_image',
            field=models.ImageField(upload_to=event_attendees.models.imageuploadeto, verbose_name='Profile Picture'),
        ),
    ]
