# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenueDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_description', models.TextField()),
                ('venue_postcode', models.CharField(max_length=10)),
                ('venue_telephone', models.CharField(max_length=12)),
                ('venue_email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Venue Detail',
                'db_table': 'demo_venue_details',
                'managed': True,
                'verbose_name_plural': 'Venue Details',
            },
        ),
    ]
