# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import event_venue.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvenuedetails',
            name='venue_photo',
            field=models.ImageField(blank=True, upload_to=event_venue.models.imageuploadeto),
        ),
    ]
