# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_attendees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Session',
                'db_table': 'demo_event_sessions',
                'managed': True,
                'verbose_name_plural': 'Event Sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionAttendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_attendee_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_attendees.AttendeeDetails', to_field='attendee_uid')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_sessions.EventSessions', to_field='session_uid')),
            ],
            options={
                'verbose_name': 'Session Attendee',
                'db_table': 'demo_session_attendees',
                'managed': True,
                'verbose_name_plural': 'Session Attendees',
            },
        ),
    ]
