# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspeakers',
            name='speaker_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_sessions.EventSessions'),
        ),
    ]
