# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import event_speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sessions', '0001_initial'),
        ('event_speakers', '0002_auto_20170211_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspeakers',
            name='speaker_topic',
        ),
        migrations.RemoveField(
            model_name='eventspeakers',
            name='talk_date',
        ),
        migrations.AddField(
            model_name='eventspeakers',
            name='speaker_confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='eventspeakers',
            name='speaker_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_sessions.EventSessions', verbose_name='Leading Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventspeakers',
            name='speaker_image',
            field=models.ImageField(blank=True, upload_to=event_speakers.models.imageuploadeto, verbose_name='Speaker Image'),
        ),
    ]
